import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'app.name': 'PartyPool',
    'auth.welcome': 'Welcome back!',
    'auth.create': 'Create your account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.noAccount': "Don't have an account? Sign up",
    'auth.hasAccount': 'Already have an account? Sign in',
    'dashboard.title': 'Your Events',
    'dashboard.subtitle': 'Manage your celebrations and track contributions',
    'dashboard.createEvent': 'Create Event',
    'dashboard.noEvents': 'No events yet',
    'dashboard.noEventsDesc': 'Create your first celebration event to get started',
    'dashboard.firstEvent': 'Create Your First Event',
    'dashboard.signOut': 'Sign Out',
    'dashboard.goal': 'Goal',
    'dashboard.deleteEvent': 'Delete Event',
    'dashboard.editEvent': 'Edit Event',
    'dashboard.confirmDelete': 'Are you sure you want to delete this event? This action cannot be undone.',
    'dashboard.deleting': 'Deleting...',
    'event.create': 'Create New Event',
    'event.edit': 'Edit Event',
    'event.deleteEvent': 'Delete Event',
    'event.updating': 'Updating...',
    'event.updateSuccess': 'Event updated successfully!',
    'event.saveChanges': 'Save Changes',
    'event.celebrantName': 'Celebrant Name',
    'event.celebrantPlaceholder': 'Who are we celebrating?',
    'event.celebrantImage': "Celebrant's Photo",
    'event.celebrantImagePlaceholder': 'Paste image URL',
    'event.imageUrl': 'URL',
    'event.imageUpload': 'Upload File',
    'event.uploadImage': 'Choose an image',
    'event.imagePreview': 'Preview',
    'event.imageTooBig': 'Image too large. Maximum size: 2MB',
    'event.celebrantBadge': 'Celebrant',
    'event.eventDate': 'Event Date',
    'event.eventTime': 'Event Time',
    'event.location': 'Location/Address',
    'event.locationPlaceholder': 'Where is the celebration?',
    'event.description': 'Description',
    'event.descriptionPlaceholder': 'Tell us about the celebration...',
    'event.budgetGoal': 'Budget Goal',
    'event.currency': 'Currency',
    'event.giftUrl': 'Gift Link',
    'event.giftUrlPlaceholder': 'Paste a link to the gift (e.g., Amazon)',
    'event.paypalEmail': 'PayPal Email or Username PayPal.me',
    'event.paypalEmailPlaceholder': 'email@example.com or username',
    'event.satispayId': 'Satispay Phone/ID',
    'event.satispayIdPlaceholder': '+39 123 456 7890 or username',
    'event.creating': 'Creating...',
    'event.giftPreview': 'Gift Preview',
    'event.viewGift': 'View Gift',
    'event.payWithPayPal': 'Pay with PayPal',
    'event.payWithSatispay': 'Pay with Satispay',
    'event.satispayPopupTitle': 'Pay with Satispay',
    'event.satispayPopupDesc': 'Open your Satispay app and send the payment to:',
    'event.copyNumber': 'Copy Number',
    'event.numberCopied': 'Number copied!',
    'event.shareWhatsApp': 'Share on WhatsApp',
    'event.whatsappMessage': 'Hi! Join me in celebrating {name} on PartyPool! Click here to see details and contribute: {url}',
    'event.showQR': 'Show QR Code',
    'event.qrTitle': 'Scan to Contribute',
    'event.qrDesc': 'Guests can scan this QR code with their phone to quickly access the event and contribute.',
    'event.back': 'Back to Dashboard',
    'event.backButton': 'Back',
    'event.notFound': 'Event Not Found',
    'event.notFoundDesc': "This event doesn't exist or has been removed.",
    'event.progress': 'Progress',
    'event.reached': 'reached',
    'event.contribute': 'Contribute',
    'event.leaveWish': 'Leave a Wish',
    'event.contributions': 'Recent Contributions',
    'event.wishes': 'Wishes & Messages',
    'event.noContributions': 'No contributions yet. Be the first!',
    'event.noWishes': 'No messages yet. Share your wishes!',
    'event.contributionType': 'Contribution Type',
    'event.contributionFree': 'Free Contribution',
    'event.contributionFreeDesc': 'Guests choose their amount',
    'event.contributionEqualShares': 'Equal Shares',
    'event.contributionEqualSharesDesc': 'Split evenly among friends',
    'event.participantsCount': 'Number of Participants',
    'event.participantsPlaceholder': 'How many friends will contribute?',
    'event.shareAmount': 'Each friend will contribute:',
    'contribution.title': 'Make a Contribution',
    'contribution.yourName': 'Your Name',
    'contribution.amount': 'Amount',
    'contribution.message': 'Message (optional)',
    'contribution.messagePlaceholder': 'Add a personal message...',
    'contribution.anonymous': 'Remain Anonymous',
    'contribution.anonymousHelp': 'Your name will appear as "A friend"',
    'contribution.note': 'This is a simulated contribution. In a production environment, this would integrate with a payment processor.',
    'contribution.submit': 'Contribute',
    'contribution.processing': 'Processing...',
    'contribution.success': 'Thank you for your contribution!',
    'contribution.addSupport': 'Add €1 to support PartyPool',
    'contribution.addSupportDesc': 'This extra euro helps keep the app free for everyone and will be managed by the organizer.',
    'contribution.totalAmount': 'Total Amount',
    'wish.title': 'Leave a Wish',
    'wish.yourName': 'Your Name',
    'wish.message': 'Your Message',
    'wish.messagePlaceholder': 'Share your birthday wishes, congratulations, or celebratory message...',
    'wish.send': 'Send Wish',
    'wish.sending': 'Sending...',
    'common.loading': 'Loading...',
    'landing.badge': '100% Free',
    'landing.heroTitle': 'Group gifts, hassle-free.',
    'landing.heroSubtitle': 'Create your page, collect contributions, and make the perfect gift happen.',
    'landing.cta': 'Get Started',
    'landing.signIn': 'Sign In',
    'landing.myEvents': 'My Events',
    'landing.howItWorksTitle': 'How It Works',
    'landing.step1Title': '1. Create',
    'landing.step1Description': 'Add the party details and link to the gift.',
    'landing.step2Title': '2. Share',
    'landing.step2Description': 'Send the link to guests with one click.',
    'landing.step3Title': '3. Celebrate',
    'landing.step3Description': 'Receive contributions via PayPal/Satispay and read the wishes.',
    'landing.faqTitle': 'Frequently Asked Questions',
    'landing.faq1Question': 'How much does PartyPool cost?',
    'landing.faq1Answer': "It's completely free for both organizers and guests.",
    'landing.faq2Question': 'Does PartyPool take a commission?',
    'landing.faq2Answer': 'No. Money goes directly from the guest to the organizer via the chosen services (PayPal/Satispay).',
    'landing.faq3Question': 'Do I have to include an Amazon link?',
    'landing.faq3Answer': 'No, you can insert any link or just a description of the desired gift.',
    'landing.faq4Question': 'Is my data safe?',
    'landing.faq4Answer': 'Absolutely. We use Supabase for secure and encrypted data management.',
    'footer.tagline': 'The easiest and most fun way to organize group gifts.',
    'footer.buyCoffee': 'Buy me a coffee',
    'footer.quickLinks': 'Quick Links',
    'footer.ctaTitle': 'Want to organize the perfect gift too?',
    'footer.ctaDescription': 'Create your event in minutes and start collecting contributions.',
    'footer.ctaButton': 'Start now, it\'s free!',
    'footer.copyright': 'All rights reserved',
    'footer.madeWith': 'Created with ❤️ to make your moments special',
    'goalReached.title': 'Congratulations! Goal Reached!',
    'goalReached.message': 'The gift for {name} is now a reality!',
    'goalReached.celebration': 'Mission Accomplished',
    'goalReached.supportTitle': 'Did PartyPool help you?',
    'goalReached.supportMessage': 'PartyPool saved you time and stress? If you like, support the project with just €1 to help us keep it free for everyone. Buy us a coffee!',
    'goalReached.supportButton': 'Support PartyPool (€1)',
    'goalReached.maybeLater': 'Maybe later',
    'goalReached.badge': 'Goal Reached! Support PartyPool',
    'piggybank.title': 'PartyPool Support Piggybank',
    'piggybank.description': 'Thanks to your friends who added the support contribution!',
    'piggybank.totalCollected': 'Total Collected for PartyPool',
    'piggybank.sendSupport': 'Send Support to PartyPool ☕',
    'piggybank.supporterBadge': 'Official PartyPool Supporter',
    'piggybank.thankYou': 'Thank you for keeping PartyPool free for everyone!',
  },
  it: {
    'app.name': 'PartyPool',
    'auth.welcome': 'Bentornato!',
    'auth.create': 'Crea il tuo account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signIn': 'Accedi',
    'auth.signUp': 'Registrati',
    'auth.noAccount': 'Non hai un account? Registrati',
    'auth.hasAccount': 'Hai già un account? Accedi',
    'dashboard.title': 'I Tuoi Eventi',
    'dashboard.subtitle': 'Gestisci le tue celebrazioni e monitora i contributi',
    'dashboard.createEvent': 'Crea Evento',
    'dashboard.noEvents': 'Nessun evento ancora',
    'dashboard.noEventsDesc': 'Crea il tuo primo evento celebrativo per iniziare',
    'dashboard.firstEvent': 'Crea il Tuo Primo Evento',
    'dashboard.signOut': 'Esci',
    'dashboard.goal': 'Obiettivo',
    'dashboard.deleteEvent': 'Elimina Evento',
    'dashboard.editEvent': 'Modifica Evento',
    'dashboard.confirmDelete': 'Sei sicuro di voler eliminare questo evento? Questa azione non può essere annullata.',
    'dashboard.deleting': 'Eliminazione...',
    'event.create': 'Crea Nuovo Evento',
    'event.edit': 'Modifica Evento',
    'event.deleteEvent': 'Elimina Evento',
    'event.updating': 'Aggiornamento...',
    'event.updateSuccess': 'Evento aggiornato con successo!',
    'event.saveChanges': 'Salva Modifiche',
    'event.celebrantName': 'Nome del Festeggiato',
    'event.celebrantPlaceholder': 'Chi stiamo festeggiando?',
    'event.celebrantImage': 'Foto del Festeggiato',
    'event.celebrantImagePlaceholder': 'Incolla URL immagine',
    'event.imageUrl': 'URL',
    'event.imageUpload': 'Carica File',
    'event.uploadImage': 'Scegli un\'immagine',
    'event.imagePreview': 'Anteprima',
    'event.imageTooBig': 'Immagine troppo grande. Dimensione massima: 2MB',
    'event.celebrantBadge': 'Festeggiato',
    'event.eventDate': 'Data Evento',
    'event.eventTime': 'Ora Evento',
    'event.location': 'Luogo/Indirizzo',
    'event.locationPlaceholder': 'Dove si svolge la celebrazione?',
    'event.description': 'Descrizione',
    'event.descriptionPlaceholder': 'Raccontaci della celebrazione...',
    'event.budgetGoal': 'Obiettivo Budget',
    'event.currency': 'Valuta',
    'event.giftUrl': 'Link al Regalo',
    'event.giftUrlPlaceholder': 'Incolla un link al regalo (es. Amazon)',
    'event.paypalEmail': 'Email PayPal o Username PayPal.me',
    'event.paypalEmailPlaceholder': 'email@esempio.com o username',
    'event.satispayId': 'Telefono/ID Satispay',
    'event.satispayIdPlaceholder': '+39 123 456 7890 o username',
    'event.creating': 'Creazione...',
    'event.giftPreview': 'Anteprima Regalo',
    'event.viewGift': 'Vedi Regalo',
    'event.payWithPayPal': 'Paga con PayPal',
    'event.payWithSatispay': 'Paga con Satispay',
    'event.satispayPopupTitle': 'Paga con Satispay',
    'event.satispayPopupDesc': 'Apri la tua app Satispay e invia il pagamento a:',
    'event.copyNumber': 'Copia Numero',
    'event.numberCopied': 'Numero copiato!',
    'event.shareWhatsApp': 'Condividi su WhatsApp',
    'event.whatsappMessage': 'Ciao! Partecipa anche tu al regalo per {name} su PartyPool! Clicca qui per vedere i dettagli e contribuire: {url}',
    'event.showQR': 'Mostra QR Code',
    'event.qrTitle': 'Scansiona per Contribuire',
    'event.qrDesc': 'Gli invitati possono scansionare questo QR code con il telefono per accedere rapidamente all\'evento e contribuire.',
    'event.back': 'Torna alla Dashboard',
    'event.backButton': 'Indietro',
    'event.notFound': 'Evento Non Trovato',
    'event.notFoundDesc': "Questo evento non esiste o è stato rimosso.",
    'event.progress': 'Progresso',
    'event.reached': 'raggiunto',
    'event.contribute': 'Contribuisci',
    'event.leaveWish': 'Lascia un Augurio',
    'event.contributions': 'Contributi Recenti',
    'event.wishes': 'Auguri e Messaggi',
    'event.noContributions': 'Nessun contributo ancora. Sii il primo!',
    'event.noWishes': 'Nessun messaggio ancora. Condividi i tuoi auguri!',
    'event.contributionType': 'Tipo di Contributo',
    'event.contributionFree': 'Contributo Libero',
    'event.contributionFreeDesc': 'Gli invitati scelgono il loro importo',
    'event.contributionEqualShares': 'Quote Uguali',
    'event.contributionEqualSharesDesc': 'Diviso equamente tra gli amici',
    'event.participantsCount': 'Numero di Partecipanti',
    'event.participantsPlaceholder': 'Quanti amici contribuiranno?',
    'event.shareAmount': 'Ogni amico dovrà versare:',
    'contribution.title': 'Fai un Contributo',
    'contribution.yourName': 'Il Tuo Nome',
    'contribution.amount': 'Importo',
    'contribution.message': 'Messaggio (facoltativo)',
    'contribution.messagePlaceholder': 'Aggiungi un messaggio personale...',
    'contribution.anonymous': 'Rimani Anonimo',
    'contribution.anonymousHelp': 'Il tuo nome apparirà come "Un amico"',
    'contribution.note': 'Questo è un contributo simulato. In un ambiente di produzione, questo si integrerebbe con un processore di pagamenti.',
    'contribution.submit': 'Contribuisci',
    'contribution.processing': 'Elaborazione...',
    'contribution.success': 'Grazie per il tuo contributo!',
    'contribution.addSupport': 'Aggiungi 1€ per supportare PartyPool',
    'contribution.addSupportDesc': 'Questo euro extra aiuta a mantenere l\'app gratuita per tutti e sarà gestito dall\'organizzatore.',
    'contribution.totalAmount': 'Importo Totale',
    'wish.title': 'Lascia un Augurio',
    'wish.yourName': 'Il Tuo Nome',
    'wish.message': 'Il Tuo Messaggio',
    'wish.messagePlaceholder': 'Condividi i tuoi auguri di compleanno, congratulazioni o messaggi celebrativi...',
    'wish.send': 'Invia Augurio',
    'wish.sending': 'Invio...',
    'common.loading': 'Caricamento...',
    'landing.badge': '100% Gratuito',
    'landing.heroTitle': 'Regali di gruppo, senza mal di testa.',
    'landing.heroSubtitle': 'Crea la tua pagina, raccogli i contributi e realizza il regalo perfetto.',
    'landing.cta': 'Inizia Ora',
    'landing.signIn': 'Accedi',
    'landing.myEvents': 'I miei Eventi',
    'landing.howItWorksTitle': 'Come Funziona',
    'landing.step1Title': '1. Crea',
    'landing.step1Description': 'Inserisci i dettagli della festa e il link al regalo.',
    'landing.step2Title': '2. Condividi',
    'landing.step2Description': 'Invia il link agli invitati con un click.',
    'landing.step3Title': '3. Festeggia',
    'landing.step3Description': 'Ricevi i contributi su PayPal/Satispay e leggi gli auguri.',
    'landing.faqTitle': 'Domande Frequenti',
    'landing.faq1Question': 'Quanto costa usare PartyPool?',
    'landing.faq1Answer': 'È totalmente gratuito per organizzatori e invitati.',
    'landing.faq2Question': 'PartyPool trattiene commissioni?',
    'landing.faq2Answer': 'No. I soldi vanno direttamente dal conto dell\'invitato a quello dell\'organizzatore tramite i servizi scelti (PayPal/Satispay).',
    'landing.faq3Question': 'Devo per forza inserire un link Amazon?',
    'landing.faq3Answer': 'No, puoi inserire qualsiasi link o anche solo una descrizione del regalo desiderato.',
    'landing.faq4Question': 'I miei dati sono al sicuro?',
    'landing.faq4Answer': 'Assolutamente sì. Usiamo Supabase per una gestione dei dati sicura e criptata.',
    'footer.tagline': 'Il modo più semplice e divertente per organizzare regali di gruppo.',
    'footer.buyCoffee': 'Offri un caffè',
    'footer.quickLinks': 'Link Rapidi',
    'footer.ctaTitle': 'Vuoi organizzare anche tu un regalo perfetto?',
    'footer.ctaDescription': 'Crea il tuo evento in pochi minuti e inizia a raccogliere contributi.',
    'footer.ctaButton': 'Inizia ora, è gratis!',
    'footer.copyright': 'Tutti i diritti riservati',
    'footer.madeWith': 'Creato con ❤️ per rendere speciali i tuoi momenti',
    'goalReached.title': 'Complimenti! Obiettivo Raggiunto!',
    'goalReached.message': 'Il regalo per {name} è ora realtà!',
    'goalReached.celebration': 'Missione Compiuta',
    'goalReached.supportTitle': 'PartyPool ti ha aiutato?',
    'goalReached.supportMessage': 'PartyPool ti ha aiutato a risparmiare tempo e stress? Se ti va, sostieni il progetto con solo 1€ per aiutarci a mantenerlo gratuito per tutti. Offrici un caffè!',
    'goalReached.supportButton': 'Sostieni PartyPool (€1)',
    'goalReached.maybeLater': 'Forse più tardi',
    'goalReached.badge': 'Obiettivo raggiunto! Sostieni PartyPool',
    'piggybank.title': 'Salvadanaio Supporto PartyPool',
    'piggybank.description': 'Hai raccolto questo grazie ai tuoi amici che hanno aggiunto il contributo di supporto!',
    'piggybank.totalCollected': 'Totale Raccolto per PartyPool',
    'piggybank.sendSupport': 'Gira il supporto a PartyPool ☕',
    'piggybank.supporterBadge': 'Sostenitore Ufficiale di PartyPool',
    'piggybank.thankYou': 'Grazie per mantenere PartyPool gratuito per tutti!',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'it' || saved === 'en') ? saved : 'it';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
