import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'app.name': 'PartyPool',
    'auth.welcome': 'Welcome back!',
    'auth.create': 'Create your account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.noAccount': "Don't have an account? Sign up",
    'auth.hasAccount': 'Already have an account? Sign in',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.resetPassword': 'Reset Password',
    'auth.backToLogin': 'Back to login',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.resetEmailSent': 'Done! Check your email, click the link and you can choose a new password right away.',
    'auth.resetEmailSentShort': 'Email sent! Check your inbox.',
    'auth.newPassword': 'New Password',
    'auth.savePassword': 'Save Password',
    'auth.passwordUpdated': 'Password updated successfully! You can now sign in with your new password.',
    'auth.resetTitle': 'Reset your password',
    'auth.resetDescription': 'Enter your email address and we\'ll send you a link to reset your password.',
    'dashboard.title': 'Your Events',
    'dashboard.subtitle': 'Manage your celebrations and track contributions',
    'dashboard.createEvent': 'Create Event',
    'dashboard.noEvents': 'No events yet',
    'dashboard.noEventsDesc': 'Create your first celebration event to get started',
    'dashboard.firstEvent': 'Create Your First Event',
    'dashboard.signOut': 'Sign Out',
    'dashboard.goal': 'Goal',
    'dashboard.deleteEvent': 'Delete Event',
    'dashboard.editEvent': 'Edit Event',
    'dashboard.confirmDelete': 'Are you sure you want to delete this event? This action cannot be undone.',
    'dashboard.deleting': 'Deleting...',
    'event.create': 'Create New Event',
    'event.edit': 'Edit Event',
    'event.deleteEvent': 'Delete Event',
    'event.updating': 'Updating...',
    'event.updateSuccess': 'Event updated successfully!',
    'event.saveChanges': 'Save Changes',
    'event.celebrantName': 'Celebrant Name',
    'event.celebrantPlaceholder': 'Who are we celebrating?',
    'event.celebrantImage': "Celebrant's Photo",
    'event.celebrantImagePlaceholder': 'Paste image URL',
    'event.imageUrl': 'URL',
    'event.imageUpload': 'Upload File',
    'event.uploadImage': 'Choose an image',
    'event.imagePreview': 'Preview',
    'event.imageTooBig': 'Image too large. Maximum size: 10MB',
    'event.celebrantBadge': 'Celebrant',
    'event.eventDate': 'Event Date',
    'event.eventTime': 'Event Time',
    'event.location': 'Location/Address',
    'event.locationPlaceholder': 'Where is the celebration?',
    'event.description': 'Description',
    'event.descriptionPlaceholder': 'Tell us about the celebration...',
    'event.budgetGoal': 'Budget Goal',
    'event.currency': 'Currency',
    'event.giftUrl': 'Gift Link',
    'event.giftUrlPlaceholder': 'Paste a link to the gift (e.g., Amazon)',
    'event.paypalEmail': 'PayPal Email',
    'event.paypalEmailPlaceholder': 'esempio@email.it',
    'event.satispayId': 'Satispay Phone/ID',
    'event.satispayIdPlaceholder': '+39 123 456 7890 or username',
    'event.creating': 'Creating...',
    'event.giftPreview': 'Gift Preview',
    'event.viewGift': 'View Gift',
    'event.payWithPayPal': 'Pay with PayPal',
    'event.payWithSatispay': 'Pay with Satispay',
    'event.satispayPopupTitle': 'Pay with Satispay',
    'event.satispayPopupDesc': 'Open your Satispay app and send the payment to:',
    'event.copyNumber': 'Copy Number',
    'event.numberCopied': 'Number copied!',
    'event.shareWhatsApp': 'Share on WhatsApp',
    'event.whatsappMessage': 'Hi! Join me in celebrating {name} on PartyPool! Click here to see details and contribute: {url}',
    'event.showQR': 'Show QR Code',
    'event.qrTitle': 'Scan to Contribute',
    'event.qrDesc': 'Guests can scan this QR code with their phone to quickly access the event and contribute.',
    'event.back': 'Back to Dashboard',
    'event.backButton': 'Back',
    'event.notFound': 'Event Not Found',
    'event.notFoundDesc': "This event doesn't exist or has been removed.",
    'event.progress': 'Progress',
    'event.reached': 'reached',
    'event.contribute': 'Contribute',
    'event.leaveWish': 'Leave a Wish',
    'event.recentContributions': 'Recent Contributions',
    'event.wishes': 'Wishes & Messages',
    'event.noContributions': 'No contributions yet. Be the first!',
    'event.noWishes': 'No messages yet. Share your wishes!',
    'event.contributionType': 'Contribution Type',
    'event.contributionFree': 'Free Contribution',
    'event.contributionFreeDesc': 'Guests choose their amount',
    'event.contributionEqualShares': 'Equal Shares',
    'event.contributionEqualSharesDesc': 'Split evenly among friends',
    'event.participantsCount': 'Number of Participants',
    'event.participantsPlaceholder': 'How many friends will contribute?',
    'event.shareAmount': 'Each friend will contribute:',
    'event.draftRecovered': 'We recovered the data you had entered',
    'event.draftRecoveredDesc': 'You can continue from where you left off.',
    'event.amazonLinkValid': 'Valid Amazon link',
    'contribution.title': 'Make a Contribution',
    'contribution.name': 'Your Name',
    'contribution.amount': 'Amount',
    'contribution.message': 'Message (optional)',
    'contribution.messageText': 'Add a personal message...',
    'contribution.anonymous': 'Remain Anonymous',
    'contribution.anonymousHelp': 'Your name will appear as "A friend"',
    'contribution.submit': 'Contribute',
    'contribution.processing': 'Processing...',
    'contribution.success': 'Thank you for your contribution!',
    'contribution.addSupport': 'Add €1 to support PartyPool',
    'contribution.addSupportDesc': 'This extra euro helps keep the app free for everyone and will be managed by the organizer.',
    'contribution.totalAmount': 'Total Amount',
    'contribution.paymentMethod': 'How do you want to contribute?',
    'contribution.paymentMethodDesc': 'Choose whether to send your contribution digitally or deliver it in person',
    'contribution.digitalPayment': 'Digital Payment',
    'contribution.digitalPaymentDesc': 'PayPal, Satispay or bank transfer',
    'contribution.cashPayment': 'Cash Payment',
    'contribution.cashPaymentDesc': 'I will pay in cash directly to {organizer}',
    'contribution.recommended': 'Recommended',
    'contribution.cashPromiseNote': 'Your contribution will be marked as "promised" until {organizer} confirms receiving the payment.',
    'contribution.setReminder': 'Remind me to bring the money to the party',
    'contribution.reminderSet': 'Reminder set',
    'contribution.notificationPermissionRequired': 'To set reminders, you must enable notifications in your browser',
    'wish.title': 'Leave a Wish',
    'wish.yourName': 'Your Name',
    'wish.message': 'Your Message',
    'wish.messagePlaceholder': 'Share your birthday wishes, congratulations, or celebratory message...',
    'wish.send': 'Send Wish',
    'wish.sending': 'Sending...',
    'common.loading': 'Loading...',
    'landing.badge': '100% Free',
    'landing.heroTitle': 'Group gifts, hassle-free.',
    'landing.heroSubtitle': 'Create your page, collect contributions, and make the perfect gift happen.',
    'landing.cta': 'Get Started',
    'landing.signIn': 'Sign In',
    'landing.myEvents': 'My Events',
    'landing.howItWorksTitle': 'How It Works',
    'landing.step1Title': '1. Create',
    'landing.step1Description': 'Add the party details and link to the gift.',
    'landing.step2Title': '2. Share',
    'landing.step2Description': 'Send the link to guests with one click.',
    'landing.step3Title': '3. Celebrate',
    'landing.step3Description': 'Receive contributions via PayPal/Satispay and read the wishes.',
    'landing.faqTitle': 'Frequently Asked Questions',
    'landing.faqSubtitle': 'Find answers to all your questions about how PartyPool works',
    'landing.faqButton': 'View All FAQs',
    'landing.faq1Question': 'How much does PartyPool cost?',
    'landing.faq1Answer': "It's completely free for both organizers and guests.",
    'landing.faq2Question': 'Does PartyPool take a commission?',
    'landing.faq2Answer': 'No. Money goes directly from the guest to the organizer via the chosen services (PayPal/Satispay).',
    'landing.faq3Question': 'Do I have to include an Amazon link?',
    'landing.faq3Answer': 'No, you can insert any link or just a description of the desired gift.',
    'landing.faq4Question': 'Is my data safe?',
    'landing.faq4Answer': 'Absolutely. We use Supabase for secure and encrypted data management.',
    'footer.tagline': 'The easiest and most fun way to organize group gifts.',
    'footer.buyCoffee': 'Buy me a coffee',
    'footer.quickLinks': 'Quick Links',
    'footer.ctaTitle': 'Want to organize the perfect gift too?',
    'footer.ctaDescription': 'Create your event in minutes and start collecting contributions.',
    'footer.ctaButton': 'Start now, it\'s free!',
    'footer.copyright': 'All rights reserved',
    'footer.madeWith': 'Created with ❤️ to make your moments special',
    'goalReached.title': 'Congratulations! Goal Reached!',
    'goalReached.message': 'The gift for {name} is now a reality!',
    'goalReached.celebration': 'Mission Accomplished',
    'goalReached.supportTitle': 'Did PartyPool help you?',
    'goalReached.supportMessage': 'PartyPool saved you time and stress? If you like, support the project with just €1 to help us keep it free for everyone. Buy us a coffee!',
    'goalReached.supportButton': 'Support PartyPool (€1)',
    'goalReached.maybeLater': 'Maybe later',
    'goalReached.badge': 'Goal Reached! Support PartyPool',
    'piggybank.title': 'PartyPool Support Piggybank',
    'piggybank.description': 'Thanks to your friends who added the support contribution!',
    'piggybank.totalCollected': 'Total Collected for PartyPool',
    'piggybank.sendSupport': 'Send Support to PartyPool ☕',
    'piggybank.supporterBadge': 'Official PartyPool Supporter',
    'piggybank.thankYou': 'Thank you for keeping PartyPool free for everyone!',
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': 'Create the perfect group gift in three simple steps',
    'howItWorks.step1Title': 'Create Your Event',
    'howItWorks.step1Description': 'Set up your celebration in minutes. Add party details, choose the gift, set your budget goal, and add your payment info (PayPal or Satispay). It\'s quick, simple, and free.',
    'howItWorks.step2Title': 'Invite Your Friends',
    'howItWorks.step2Description': 'Share your event link via WhatsApp, email, or QR code. Friends can contribute any amount they want directly through PayPal or Satispay. No sign-up required for guests.',
    'howItWorks.step3Title': 'Buy the Gift',
    'howItWorks.step3Description': 'Watch contributions come in real-time. Once you reach your goal, purchase the gift and make the celebration unforgettable. Read all the wishes and messages from your friends.',
    'howItWorks.ctaTitle': 'Ready to Create Your Event?',
    'howItWorks.ctaSubtitle': 'Join thousands of organizers making gift-giving simple and fun',
    'howItWorks.ctaButton': 'Create Your Event Now',
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Everything you need to know about PartyPool',
    'faq.question1': 'Does PartyPool handle the money?',
    'faq.answer1': 'No, we never handle money directly. Contributions go straight from your guests to you via PayPal or Satispay. PartyPool simply helps coordinate the collection and tracks the progress toward your goal.',
    'faq.question2': 'How much does PartyPool cost?',
    'faq.answer2': 'PartyPool is completely free for both organizers and guests. We don\'t charge any fees or commissions. To keep the service free, we earn a small commission as an Amazon Affiliate when gifts are purchased through Amazon links.',
    'faq.question3': 'Do I have to buy the gift on Amazon?',
    'faq.answer3': 'Not at all! You can add any link (Amazon, other stores, or no link at all). The Amazon affiliate feature simply helps support PartyPool when you choose to use it, but it\'s completely optional.',
    'faq.question4': 'Can I share links to external stores?',
    'faq.answer4': 'Yes! You can add links to any online or physical store. If you prefer, you can just describe the gift without adding any link. It\'s completely flexible.',
    'faq.ctaTitle': 'Still Have Questions?',
    'faq.ctaSubtitle': 'The best way to understand is to try it yourself',
    'faq.ctaButton': 'Create Your Event Now',
    'dashboard.myEvents': 'YOUR EVENTS',
    'dashboard.myGifts': 'YOUR GIFTS',
    'dashboard.collected': 'collected',
    'event.theGift': 'The Gift',
    'event.seeGift': 'See the gift',
    'event.totalIncome': 'Total Income (Gifts + Coffee):',
    'event.contributions': 'Contributions',
    'event.haveCoffee': 'Offered a coffee!',
    'event.cashConfirm': 'Confirm',
    'event.coffeesOffered': 'Coffees offered',
    'event.coffeeOffered': 'Coffee offered',
    'contribution.makeGift': 'Make a gift',
    'contribution.yourName': 'Your Name',
    'contribution.namePlaceholder': 'E.g.: Marco Rossi',
    'contribution.hideName': 'Hide my name',
    'contribution.howMuch': 'How much are you gifting?',
    'contribution.writeMessage': 'Write a message',
    'contribution.messagePlaceholder': 'Share your wishes...',
    'contribution.offerCoffee': 'Offer a coffee? (+1.00€)',
    'contribution.supportPlatform': 'To support the platform',
    'contribution.onlinePayment': 'Online Payment',
    'contribution.cashInHand': 'Cash in hand',
    'contribution.payWithPayPal': 'Pay with PayPal',
    'contribution.payWithSatispay': 'Pay with Satispay',
    'contribution.saving': 'SAVING...',
    'contribution.confirmGift': 'CONFIRM GIFT',
    'contribution.thankYou': 'Thank you!',
    'contribution.saveMemory': 'Want to save this memory?',
    'contribution.saveMemoryDesc': 'Create a free account to track all the gifts you make over time. A timeline of your generosity among friends!',
    'contribution.saveToProfile': 'Save to my profile',
    'contribution.noThanks': 'No thanks, continue',
    'history.loading': 'Loading...',
    'history.noGifts': 'No gifts yet',
    'history.noGiftsDesc': 'When you contribute to an event, you\'ll see your history of generosity here!',
    'history.yourTimeline': 'Your Timeline',
    'history.giftsContributed': 'Gifts you contributed to',
    'history.totalContributed': 'Total Contributed',
    'history.in': 'in',
    'history.gift': 'gift',
    'history.gifts': 'gifts',
    'history.giftFor': 'Gift for',
    'history.coffee': 'coffee',
    'history.confirmed': 'Confirmed',
    'history.pending': 'Pending',
    'history.online': 'Online',
    'history.cash': 'Cash',
    'history.viewEvent': 'View event',
    'event.linkCopied': 'Link copied to clipboard!',
    'event.partyFor': 'Party for',
    'event.deleteError': 'Failed to delete event.',
    'event.cashPaymentError': 'Error confirming payment',
  },
  it: {
    'app.name': 'PartyPool',
    'auth.welcome': 'Bentornato!',
    'auth.create': 'Crea il tuo account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signIn': 'Accedi',
    'auth.signUp': 'Registrati',
    'auth.noAccount': 'Non hai un account? Registrati',
    'auth.hasAccount': 'Hai già un account? Accedi',
    'auth.forgotPassword': 'Password dimenticata?',
    'auth.resetPassword': 'Recupera Password',
    'auth.backToLogin': 'Torna al login',
    'auth.sendResetLink': 'Ricevi link di accesso',
    'auth.resetEmailSent': 'Fatto! Controlla la tua email, clicca sul link e potrai scegliere subito una nuova password.',
    'auth.resetEmailSentShort': 'Email inviata! Controlla la tua casella.',
    'auth.newPassword': 'Nuova Password',
    'auth.savePassword': 'Salva',
    'auth.passwordUpdated': 'Password aggiornata con successo! Ora puoi accedere con la nuova password.',
    'auth.resetTitle': 'Recupera la tua password',
    'auth.resetDescription': 'Inserisci la tua email e ti invieremo un link per reimpostare la password.',
    'dashboard.title': 'I Tuoi Eventi',
    'dashboard.subtitle': 'Gestisci le tue celebrazioni e monitora i contributi',
    'dashboard.createEvent': 'Crea Evento',
    'dashboard.noEvents': 'Nessun evento ancora',
    'dashboard.noEventsDesc': 'Crea il tuo primo evento celebrativo per iniziare',
    'dashboard.firstEvent': 'Crea il Tuo Primo Evento',
    'dashboard.signOut': 'Esci',
    'dashboard.goal': 'Obiettivo',
    'dashboard.deleteEvent': 'Elimina Evento',
    'dashboard.editEvent': 'Modifica Evento',
    'dashboard.confirmDelete': 'Sei sicuro di voler eliminare questo evento? Questa azione non può essere annullata.',
    'dashboard.deleting': 'Eliminazione...',
    'event.create': 'Crea Nuovo Evento',
    'event.edit': 'Modifica Evento',
    'event.deleteEvent': 'Elimina Evento',
    'event.updating': 'Aggiornamento...',
    'event.updateSuccess': 'Evento aggiornato con successo!',
    'event.saveChanges': 'Salva Modifiche',
    'event.celebrantName': 'Nome del Festeggiato',
    'event.celebrantPlaceholder': 'Chi stiamo festeggiando?',
    'event.celebrantImage': 'Foto del Festeggiato',
    'event.celebrantImagePlaceholder': 'Incolla URL immagine',
    'event.imageUrl': 'URL',
    'event.imageUpload': 'Carica File',
    'event.uploadImage': 'Scegli un\'immagine',
    'event.imagePreview': 'Anteprima',
    'event.imageTooBig': 'Immagine troppo grande. Dimensione massima: 10MB',
    'event.celebrantBadge': 'Festeggiato',
    'event.eventDate': 'Data Evento',
    'event.eventTime': 'Ora Evento',
    'event.location': 'Luogo/Indirizzo',
    'event.locationPlaceholder': 'Dove si svolge la celebrazione?',
    'event.description': 'Descrizione',
    'event.descriptionPlaceholder': 'Raccontaci della celebrazione...',
    'event.budgetGoal': 'Obiettivo Budget',
    'event.currency': 'Valuta',
    'event.giftUrl': 'Link al Regalo',
    'event.giftUrlPlaceholder': 'Incolla un link al regalo (es. Amazon)',
    'event.paypalEmail': 'Email PayPal',
    'event.paypalEmailPlaceholder': 'esempio@email.it',
    'event.satispayId': 'Telefono/ID Satispay',
    'event.satispayIdPlaceholder': '+39 123 456 7890 o username',
    'event.creating': 'Creazione...',
    'event.giftPreview': 'Anteprima Regalo',
    'event.viewGift': 'Vedi Regalo',
    'event.payWithPayPal': 'Paga con PayPal',
    'event.payWithSatispay': 'Paga con Satispay',
    'event.satispayPopupTitle': 'Paga con Satispay',
    'event.satispayPopupDesc': 'Apri la tua app Satispay e invia il pagamento a:',
    'event.copyNumber': 'Copia Numero',
    'event.numberCopied': 'Numero copiato!',
    'event.shareWhatsApp': 'Condividi su WhatsApp',
    'event.whatsappMessage': 'Ciao! Partecipa anche tu al regalo per {name} su PartyPool! Clicca qui per vedere i dettagli e contribuire: {url}',
    'event.showQR': 'Mostra QR Code',
    'event.qrTitle': 'Scansiona per Contribuire',
    'event.qrDesc': 'Gli invitati possono scansionare questo QR code con il telefono per accedere rapidamente all\'evento e contribuire.',
    'event.back': 'Torna alla Dashboard',
    'event.backButton': 'Indietro',
    'event.notFound': 'Evento Non Trovato',
    'event.notFoundDesc': "Questo evento non esiste o è stato rimosso.",
    'event.progress': 'Progresso',
    'event.reached': 'raggiunto',
    'event.contribute': 'Contribuisci',
    'event.leaveWish': 'Lascia un Augurio',
    'event.recentContributions': 'Contributi Recenti',
    'event.wishes': 'Auguri e Messaggi',
    'event.noContributions': 'Nessun contributo ancora. Sii il primo!',
    'event.noWishes': 'Nessun messaggio ancora. Condividi i tuoi auguri!',
    'event.contributionType': 'Tipo di Contributo',
    'event.contributionFree': 'Contributo Libero',
    'event.contributionFreeDesc': 'Gli invitati scelgono il loro importo',
    'event.contributionEqualShares': 'Quote Uguali',
    'event.contributionEqualSharesDesc': 'Diviso equamente tra gli amici',
    'event.participantsCount': 'Numero di Partecipanti',
    'event.participantsPlaceholder': 'Quanti amici contribuiranno?',
    'event.shareAmount': 'Ogni amico dovrà versare:',
    'event.draftRecovered': 'Abbiamo recuperato i dati che avevi inserito',
    'event.draftRecoveredDesc': 'Puoi continuare da dove avevi lasciato.',
    'event.amazonLinkValid': 'Link Amazon valido',
    'contribution.title': 'Fai un Contributo',
    'contribution.name': 'Il Tuo Nome',
    'contribution.amount': 'Importo',
    'contribution.message': 'Messaggio (facoltativo)',
    'contribution.messageText': 'Aggiungi un messaggio personale...',
    'contribution.anonymous': 'Rimani Anonimo',
    'contribution.anonymousHelp': 'Il tuo nome apparirà come "Un amico"',
    'contribution.submit': 'Contribuisci',
    'contribution.processing': 'Elaborazione...',
    'contribution.success': 'Grazie per il tuo contributo!',
    'contribution.addSupport': 'Aggiungi 1€ per supportare PartyPool',
    'contribution.addSupportDesc': 'Questo euro extra aiuta a mantenere l\'app gratuita per tutti e sarà gestito dall\'organizzatore.',
    'contribution.totalAmount': 'Importo Totale',
    'contribution.paymentMethod': 'Come vuoi contribuire?',
    'contribution.paymentMethodDesc': 'Scegli se inviare la tua quota digitalmente o consegnarla a mano',
    'contribution.digitalPayment': 'Pagamento Digitale',
    'contribution.digitalPaymentDesc': 'PayPal, Satispay o bonifico',
    'contribution.cashPayment': 'Pagamento in Contanti',
    'contribution.cashPaymentDesc': 'Pagherò in contanti direttamente a {organizer}',
    'contribution.recommended': 'Consigliato',
    'contribution.cashPromiseNote': 'La tua quota verrà segnata come "promessa" fino a quando {organizer} non confermerà di aver ricevuto il pagamento.',
    'contribution.setReminder': 'Ricordami di portare i soldi alla festa',
    'contribution.reminderSet': 'Promemoria impostato',
    'contribution.notificationPermissionRequired': 'Per impostare promemoria, devi abilitare le notifiche nel browser',
    'wish.title': 'Lascia un Augurio',
    'wish.yourName': 'Il Tuo Nome',
    'wish.message': 'Il Tuo Messaggio',
    'wish.messagePlaceholder': 'Condividi i tuoi auguri di compleanno, congratulazioni o messaggi celebrativi...',
    'wish.send': 'Invia Augurio',
    'wish.sending': 'Invio...',
    'common.loading': 'Caricamento...',
    'landing.badge': '100% Gratuito',
    'landing.heroTitle': 'Regali di gruppo, senza mal di testa.',
    'landing.heroSubtitle': 'Crea la tua pagina, raccogli i contributi e realizza il regalo perfetto.',
    'landing.cta': 'Inizia Ora',
    'landing.signIn': 'Accedi',
    'landing.myEvents': 'I miei Eventi',
    'landing.howItWorksTitle': 'Come Funziona',
    'landing.step1Title': '1. Crea',
    'landing.step1Description': 'Inserisci i dettagli della festa e il link al regalo.',
    'landing.step2Title': '2. Condividi',
    'landing.step2Description': 'Invia il link agli invitati con un click.',
    'landing.step3Title': '3. Festeggia',
    'landing.step3Description': 'Ricevi i contributi su PayPal/Satispay e leggi gli auguri.',
    'landing.faqTitle': 'Domande Frequenti',
    'landing.faqSubtitle': 'Trova le risposte a tutte le tue domande su come funziona PartyPool',
    'landing.faqButton': 'Vedi Tutte le FAQ',
    'landing.faq1Question': 'Quanto costa usare PartyPool?',
    'landing.faq1Answer': 'È totalmente gratuito per organizzatori e invitati.',
    'landing.faq2Question': 'PartyPool trattiene commissioni?',
    'landing.faq2Answer': 'No. I soldi vanno direttamente dal conto dell\'invitato a quello dell\'organizzatore tramite i servizi scelti (PayPal/Satispay).',
    'landing.faq3Question': 'Devo per forza inserire un link Amazon?',
    'landing.faq3Answer': 'No, puoi inserire qualsiasi link o anche solo una descrizione del regalo desiderato.',
    'landing.faq4Question': 'I miei dati sono al sicuro?',
    'landing.faq4Answer': 'Assolutamente sì. Usiamo Supabase per una gestione dei dati sicura e criptata.',
    'footer.tagline': 'Il modo più semplice e divertente per organizzare regali di gruppo.',
    'footer.buyCoffee': 'Offri un caffè',
    'footer.quickLinks': 'Link Rapidi',
    'footer.ctaTitle': 'Vuoi organizzare anche tu un regalo perfetto?',
    'footer.ctaDescription': 'Crea il tuo evento in pochi minuti e inizia a raccogliere contributi.',
    'footer.ctaButton': 'Inizia ora, è gratis!',
    'footer.copyright': 'Tutti i diritti riservati',
    'footer.madeWith': 'Creato con ❤️ per rendere speciali i tuoi momenti',
    'goalReached.title': 'Complimenti! Obiettivo Raggiunto!',
    'goalReached.message': 'Il regalo per {name} è ora realtà!',
    'goalReached.celebration': 'Missione Compiuta',
    'goalReached.supportTitle': 'PartyPool ti ha aiutato?',
    'goalReached.supportMessage': 'PartyPool ti ha aiutato a risparmiare tempo e stress? Se ti va, sostieni il progetto con solo 1€ per aiutarci a mantenerlo gratuito per tutti. Offrici un caffè!',
    'goalReached.supportButton': 'Sostieni PartyPool (€1)',
    'goalReached.maybeLater': 'Forse più tardi',
    'goalReached.badge': 'Obiettivo raggiunto! Sostieni PartyPool',
    'piggybank.title': 'Salvadanaio Supporto PartyPool',
    'piggybank.description': 'Hai raccolto questo grazie ai tuoi amici che hanno aggiunto il contributo di supporto!',
    'piggybank.totalCollected': 'Totale Raccolto per PartyPool',
    'piggybank.sendSupport': 'Gira il supporto a PartyPool ☕',
    'piggybank.supporterBadge': 'Sostenitore Ufficiale di PartyPool',
    'piggybank.thankYou': 'Grazie per mantenere PartyPool gratuito per tutti!',
    'howItWorks.title': 'Come Funziona',
    'howItWorks.subtitle': 'Crea il regalo di gruppo perfetto in tre semplici passaggi',
    'howItWorks.step1Title': 'Crea il Tuo Evento',
    'howItWorks.step1Description': 'Imposta la tua celebrazione in pochi minuti. Aggiungi i dettagli della festa, scegli il regalo, stabilisci il tuo obiettivo e inserisci i dati di pagamento (PayPal o Satispay). È veloce, semplice e gratuito.',
    'howItWorks.step2Title': 'Invita i Tuoi Amici',
    'howItWorks.step2Description': 'Condividi il link del tuo evento via WhatsApp, email o QR code. Gli amici possono contribuire con l\'importo che preferiscono direttamente tramite PayPal o Satispay. Nessuna registrazione richiesta per gli invitati.',
    'howItWorks.step3Title': 'Compra il Regalo',
    'howItWorks.step3Description': 'Guarda i contributi arrivare in tempo reale. Una volta raggiunto l\'obiettivo, acquista il regalo e rendi la celebrazione indimenticabile. Leggi tutti gli auguri e messaggi dei tuoi amici.',
    'howItWorks.ctaTitle': 'Pronto a Creare il Tuo Evento?',
    'howItWorks.ctaSubtitle': 'Unisciti a migliaia di organizzatori che rendono il regalo semplice e divertente',
    'howItWorks.ctaButton': 'Crea Ora il Tuo Evento',
    'faq.title': 'Domande Frequenti',
    'faq.subtitle': 'Tutto quello che devi sapere su PartyPool',
    'faq.question1': 'Quanto costa usare PartyPool?',
    'faq.answer1': 'Il servizio è completamente gratuito. Non ci sono costi di iscrizione né commissioni sulle raccolte, poiché PartyPool non trattiene alcuna percentuale sui contributi.',
    'faq.question2': 'Gli invitati devono registrarsi per contribuire?',
    'faq.answer2': 'No, è possibile contribuire in pochi secondi senza account. La registrazione è facoltativa e utile solo se si desidera salvare e consultare lo storico di tutti i regali fatti nel tempo.',
    
    'faq.question3': 'Come avviene il pagamento?',
    'faq.answer3': 'PartyPool è un tramite e un coordinatore, non gestisce un portafoglio elettronico interno. L\'app ti guida a completare il pagamento direttamente tramite PayPal, Satispay o Contanti. I soldi arrivano direttamente all\'organizzatore, senza passare dai nostri sistemi.',
    
    'faq.question4': 'Posso permettere contributi in contanti?',
    'faq.answer4': 'Sì! Gli invitati possono scegliere tra "Pagamento Digitale" (PayPal/Satispay) o "Pagamento in Contanti". I contributi in contanti verranno segnati come "promessi" finché tu non confermerai manualmente di averli ricevuti.',
    
    'faq.question5': 'I miei dati di pagamento sono al sicuro?',
    'faq.answer5': 'Sì, perché PartyPool non memorizza mai i tuoi dati finanziari. Le transazioni avvengono esclusivamente sulle piattaforme esterne sicure (come PayPal o Satispay) che già conosci.',
    
    'faq.question6': 'Posso modificare un evento dopo averlo creato?',
    'faq.answer6': 'Certamente! Come organizzatore, puoi modificare tutti i dettagli (nome, data, descrizione, importi obiettivo e link al regalo) in qualsiasi momento direttamente dalla tua dashboard.',
    
    'faq.question7': 'Cosa succede se non raggiungiamo l\'obiettivo?',
    'faq.answer7': 'L\'organizzatore riceve comunque tutti i contributi raccolti. PartyPool è uno strumento di coordinamento: non ci sono obiettivi vincolanti o blocchi dei fondi.',
    
    'faq.question8': 'Come funziona la modalità "Quote Uguali"?',
    'faq.answer8': 'È semplicissimo: specifichi il costo totale del regalo e il numero di amici che parteciperanno. L\'app calcola automaticamente la quota esatta per ciascuno, eliminando ogni imbarazzo nel chiedere i soldi.',
    
    'faq.question9': 'Gli altri partecipanti possono vedere quanto ho contribuito?',
    'faq.answer9': 'Dipende dalle impostazioni dell\'organizzatore. Può scegliere di mostrare gli importi singoli, oppure nasconderli mostrando solo la lista di chi ha partecipato.',
    
    'faq.question10': 'Posso contribuire in modo anonimo?',
    'faq.answer10': 'Sì. Selezionando l\'opzione "Anonimo", il tuo nome non sarà visibile agli altri invitati, ma solo all\'organizzatore (che deve poter verificare il pagamento).',
    
    'faq.question11': 'Devo per forza comprare il regalo su Amazon?',
    'faq.answer11': 'Assolutamente no! Puoi aggiungere qualsiasi link (Amazon, altri negozi, o nessun link). La funzione di affiliazione Amazon aiuta semplicemente a supportare PartyPool quando scegli di usarla, ma è completamente opzionale.',
    
    'faq.question12': 'Posso condividere link a negozi esterni?',
    'faq.answer12': 'Sì! Puoi aggiungere link a qualsiasi negozio online o fisico. Se preferisci, puoi anche solo descrivere il regalo senza aggiungere alcun link. È completamente flessibile.',
    
    'faq.question13': 'Posso creare più eventi contemporaneamente?',
    'faq.answer13': 'Certamente! Non c\'è limite al numero di eventi che puoi organizzare. Tutti saranno comodamente gestibili dalla tua dashboard personale.',
   
    'faq.ctaTitle': 'Hai Ancora Domande?',
    'faq.ctaSubtitle': 'Il modo migliore per capire è provarlo tu stesso',
    'faq.ctaButton': 'Crea Ora il Tuo Evento',
    'dashboard.myEvents': 'I TUOI EVENTI',
    'dashboard.myGifts': 'I TUOI REGALI',
    'dashboard.collected': 'raccolti',
    'event.theGift': 'Il regalo',
    'event.seeGift': 'Vedi il regalo',
    'event.totalIncome': 'Incasso Totale (Regali + Caffè):',
    'event.contributions': 'Contributi',
    'event.haveCoffee': 'Ha offerto un caffè!',
    'event.cashConfirm': 'Conferma',
    'event.coffeesOffered': 'Caffè offerti',
    'event.coffeeOffered': 'Caffè offerto',
    'contribution.makeGift': 'Fai un regalo',
    'contribution.yourName': 'Il tuo Nome',
    'contribution.namePlaceholder': 'Esempio: Marco Rossi',
    'contribution.hideName': 'Nascondi il mio nome',
    'contribution.howMuch': 'Quanto regali?',
    'contribution.writeMessage': 'Scrivi un messaggio',
    'contribution.messagePlaceholder': 'Fai i tuoi auguri...',
    'contribution.offerCoffee': 'Offri un caffè? (+1.00€)',
    'contribution.supportPlatform': 'Per sostenere la piattaforma',
    'contribution.onlinePayment': 'Pagamento Online',
    'contribution.cashInHand': 'Contanti a mano',
    'contribution.payWithPayPal': 'Paga con PayPal',
    'contribution.payWithSatispay': 'Paga con Satispay',
    'contribution.saving': 'SALVATAGGIO...',
    'contribution.confirmGift': 'CONFERMA REGALO',
    'contribution.thankYou': 'Grazie!',
    'contribution.saveMemory': 'Vuoi salvare questo ricordo?',
    'contribution.saveMemoryDesc': 'Crea un account gratuito per tenere traccia di tutti i regali che fai nel tempo. Una timeline della tua generosità tra amici!',
    'contribution.saveToProfile': 'Salva nel mio profilo',
    'contribution.noThanks': 'No grazie, continua',
    'history.loading': 'Caricamento...',
    'history.noGifts': 'Nessun regalo ancora',
    'history.noGiftsDesc': 'Quando contribuirai a un evento, vedrai qui la tua storia di generosità!',
    'history.yourTimeline': 'La Tua Timeline',
    'history.giftsContributed': 'I regali a cui hai contribuito',
    'history.totalContributed': 'Totale Contribuito',
    'history.in': 'in',
    'history.gift': 'regalo',
    'history.gifts': 'regali',
    'history.giftFor': 'Regalo per',
    'history.coffee': 'caffè',
    'history.confirmed': 'Confermato',
    'history.pending': 'In attesa',
    'history.online': 'Online',
    'history.cash': 'Contanti',
    'history.viewEvent': 'Vedi evento',
    'event.linkCopied': 'Link copiato negli appunti!',
    'event.partyFor': 'Festa di',
    'event.deleteError': 'Failed to delete event.',
    'event.cashPaymentError': 'Errore durante la conferma del pagamento',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'it' || saved === 'en') ? saved : 'it';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
